### ISSUE TITLE
Elm example

### ISSUE THREAD

**Issue by MikeBild** [CodeCommission/dropstack-examples#3]

**Comment by CarstenKoenig** [comment]
weil ich das gerade sehe: Du hast doch bestimmt einen Container, in dem `npm` *vorhanden* ist oder?

Falls ja könnte ich versuchen Dir ein "Example" zu basteln (im Endeffekt muss nur `npm install -g elm` funktionieren ... Besser wäre aber vielleicht ein fertiger Container in dem eine feste Version vorinstalliert ist - sonst wird das so nicht mehr gehen, sobald elm-0.19 (or whatever) da ist)

**Comment by MikeBild** [comment]
Ja das wäre super cool! Ein `npm install -g elm@0.18.0` würde die Version fix setzten. Gibt es etwas an Dateien oder Konventionen das zur eindeutigen Erkennung eines Elm-Projektes möglich sind? Fällt die etwas ein?

**Comment by CarstenKoenig** [comment]
nein leider gar nicht - im Projektverzeichnis findest Du normalerweise eine `elm-package.json` (die enthält aber auch nicht unbedingt einen Namen - im Standard nur eine *"summary"*) und ein `elm-stuff`

**Comment by MikeBild** [comment]
I'm fine with a elm-package.json ;-). A good starting point for automatic Elm recognition. Let's see in your concrete example. Thank you Carsten!

**Comment by CarstenKoenig** [comment]
see https://github.com/CodeCommission/dropstack-examples/pull/10

**Comment by MikeBild** [comment]
Elm SPA with NGINX 4f51f9f7269c1913ed1160f4903271753b34d36f
