### ISSUE TITLE
Haskell example

### ISSUE THREAD

**Issue by MikeBild** [CodeCommission/dropstack-examples#9]

**Comment by CarstenKoenig** [comment]
sieht ja soweit gut aus

würde vielleicht auch

    FROM haskell
    EXPOSE 80
    RUN stack setup
    ADD . /app
    WORKDIR /app
    RUN stack install
    ENTRYPOINT ~/.local/bin$(find . -name *.cabal -print | head -n 5 | grep -o '[^/]*$' | cut -d'.' -f1)

gehen? (es sollte eigentlich nicht nötig sein, dass Programm in der Stack-Umgebung laufen zu lassen)

**Comment by MikeBild** [comment]
Thx! Adjusted with 100bf5bdb605446427ef3367b052529fae2f18f2.

What's, in your opinion, the best option to automatically recognize a Haskell project. Find a `.cabal` file for instance?

**Comment by CarstenKoenig** [comment]
for now yes - the .cabal should be fine - the only problem I see is, that some prefer to use [hpack](https://github.com/sol/hpack#readme) (a tool that will create the .cabal from a package.yaml) - in this case we would have to parse this file a bit to find the names

also the "stanzas" in the cabal file might have a different name for the executable:

it's this one:


    executable          haskell-example
    
here the name could be different from the `.cabal` and if nothing else in the ghc-args is specified this is used for the name of the produced executable

IMO it's fine to just tell people to please use the same name IMO

hpack parsing should be easy (I'm sure there is a yaml parser for whatever you use as a language) - but the cabal one *reeks* of a need to use regexes :(

**Comment by CarstenKoenig** [comment]
BTW: you want the auto-option so that the dockerfile is not really needed right?

If the user just provides it he/she can just state the file as is I think

**Comment by MikeBild** [comment]
Yes, the goal is "easy deployment" without too much `Dockerfile` hassles. But, if you like, you can deploy everything via Dockerfile. We should try to optimize the dropstack deployment platform to recognize the right deployment type for a certain development platform. Sometimes there are existing conventions, sometimes we need to define some.

ATM I'm fine with the `executable.cabal` convention. To be sure, it's better to parse the file. Is the cabal file a `yaml` file? That doesn't seems to be.

**Comment by CarstenKoenig** [comment]
no .cabal is it's own format - that's why some look for the hpack thing

**Comment by MikeBild** [comment]
Is there a way to "script" hpack based executable file recognition?

**Comment by CarstenKoenig** [comment]
if you are fine with a simple Haskell command line program then I think I could get you the info relatively easy (should be not to hard to *borrow* from what stack does to find it - there are obviouosly cabal and yaml parsers for Haskell)

but overall it should not be to hard either - we just have to look for the `executable` sections - in .cabal the generated name is just the string after it and in yaml/hpack (see here: https://github.com/hspec/sensei/blob/master/package.yaml) it's either empty (same name as the name field in the file) or you can specify it on the next line

I think I could manage to parse this in most languages ... given enough time ;)

**Comment by MikeBild** [comment]
Wow! Cool! we have enough time ... of course ;-). Thank you Carsten!
